In [1]:
%pwd

'c:\\Users\\yonas\\Desktop\\Hotel_Reservations\\research'

In [2]:
import os

In [3]:
os.chdir("../")
%pwd

'c:\\Users\\yonas\\Desktop\\Hotel_Reservations'

In [4]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("artifacts/data_transformation/train.csv")

In [6]:
data.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN34993,1,0,2,2,Meal Plan 1,0,Room_Type 1,74,2018,7,23,Offline,0,0,0,68.0,0,Not_Canceled
1,INN32715,1,0,0,1,Meal Plan 1,0,Room_Type 1,2,2018,1,21,Online,0,0,0,79.0,1,Not_Canceled
2,INN25919,2,0,1,0,Meal Plan 1,0,Room_Type 1,3,2018,5,2,Complementary,0,0,0,0.0,0,Not_Canceled
3,INN19711,2,0,0,2,Meal Plan 1,0,Room_Type 1,88,2018,10,7,Corporate,0,0,0,90.0,1,Not_Canceled
4,INN07567,2,0,2,4,Meal Plan 2,0,Room_Type 4,86,2018,7,9,Offline,0,0,0,139.6,0,Not_Canceled

In [7]:
data.columns

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [8]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    """  
    Remove unnecessary columns safely.
    Parameters:
        df (pd.DataFrame): Input dataset
    Returns:
        pd.DataFrame: Cleaned dataset  s
    """
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame")

    required_cols = ['Unnamed: 0', 'Booking_ID']
    return df.drop(columns=[c for c in required_cols if c in df.columns])   

#data.drop(columns=['Unnamed: 0', 'Booking_ID'] , inplace=True)
clean_data(data)

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,1,0,2,2,Meal Plan 1,0,Room_Type 1,74,2018,7,23,Offline,0,0,0,68.00,0,Not_Canceled
1,1,0,0,1,Meal Plan 1,0,Room_Type 1,2,2018,1,21,Online,0,0,0,79.00,1,Not_Canceled
2,2,0,1,0,Meal Plan 1,0,Room_Type 1,3,2018,5,2,Complementary,0,0,0,0.00,0,Not_Canceled
3,2,0,0,2,Meal Plan 1,0,Room_Type 1,88,2018,10,7,Corporate,0,0,0,90.00,1,Not_Canceled
4,2,0,2,4,Meal Plan 2,0,Room_Type 4,86,2018,7,9,Offline,0,0,0,139.60,0,Not_Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27201,2,0,0,1,Meal Plan 2,0,Room_Type 1,100,2017,10,16,Online,0,0,0,108.00,0,Canceled
27202,2,0,0,2,Meal Plan 1,0,Room_Type 1,42,2018,2,26,Offline,0,0,0,74.00,0,Not_Canceled
27203,2,0,1,0,Not Selected,0,Room_Type 1,102,2018,10,9,Online,0,0,0,108.00,1,Not_Canceled
27204,2,0,0,1,Not Selected,0,Room_Type 1,131,2018,7,7,Online,0,0,0,103.50,1,Not_Canceled
27205,2,0,2,2,Meal Plan 1,0,Room_Type 1,49,2018,3,6,Online,0,0,0,75.95,0,Not_Canceled

In [9]:
data.shape

(27206, 19)

In [10]:
data.shape[1] , data.shape[0]

(19, 27206)

In [22]:
#data.shape
class DataValidationError(Exception):
    pass
def validate_dataframe(df:pd.DataFrame) -> bool:
    if not isinstance(df, pd.DataFrame):
        raise TypeError("Input must be a pandas DataFrame")

    if df.empty: # df.shape[0] ==0
        raise ValueError("DataFrame is empty or Dataset is empty")
    if df.shape[0] < 1000:
        raise DataValidationError("Not enough data for training")
    if df.shape[1] < 5:
        raise ValueError("Insufficient features")
    
    return True

In [12]:
validate_dataframe(data)

True

In [13]:
# data.isnull().sum()  replaced  
def validate_missing_values(df :pd.DataFrame, threshold=0.05):
    missing_ratio = df.isnull().mean()
    
    if (missing_ratio > threshold).any():
        raise ValueError("Too many missing values detected")
validate_dataframe(data)

True

In [21]:
#data.duplicated().sum()
def check_duplicates(df:pd.DataFrame):
    dup_count = df.duplicated().sum()
    if dup_count > 0:
        raise ValueError(f"Dataset contains {dup_count} duplicate rows")
check_duplicates(data)

In [23]:
data.columns

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [26]:
data["booking_status"].value_counts(normalize=True).mul(100).round(2)

booking_status
Not_Canceled    67.15
Canceled        32.85
Name: proportion, dtype: float64

In [27]:
cat_cols = ['type_of_meal_plan','required_car_parking_space',
       'room_type_reserved','market_segment_type', 'repeated_guest','booking_status']

num_cols = ['no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights','lead_time', 'arrival_year', 'arrival_month',
       'arrival_date','no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests']